### ISSUE TITLE
MetaBCI开源信息获取咨询

### ISSUE THREAD

**Issue by lingr7** [TBC-TJU/brainda#1]
我从http://news.tju.edu.cn/info/1013/60292.htm  这里得知了MetaBCI的消息，但是我搜索寻找了一下，没有找到这个开源软件平台，请问是发布在什么平台上，以及开源方式和开源路线。
受限于资金，技术，设备，这种项目的代码贡献者可能很稀缺，但是开源至少意味着公开发布吧。

**Comment by TBC-TJU** [comment]
目前只公布了brainda，其他MetaBCI代码会逐步公开

**Comment by pingpingwuqihou** [comment]
请问您说的brainda在哪找呢，有链接可以给我一份嘛

**Comment by yushisheng** [comment]
> 

请问您说的brainda在哪找呢，有链接可以给我一份嘛

**Comment by lingr7** [comment]
brainda就是这个python代码啊。
